### ISSUE TITLE
关于订阅

### ISSUE THREAD

**Issue by CoderLengary** [qingmei2/MVI-Rhine#1]
在ViewModel里，我注意到statesObservable被转化成了一个ConnectableObservable，
```
private fun compose(): Observable<LoginViewState> {
        return intentsSubject
            .compose(intentFilter)
            .map(this::actionFromIntent)
            .compose(processorHolder.actionProcessor)
            .scan(LoginViewState.idle(), reducer)
            .switchMap(specialEventProcessor)
            .distinctUntilChanged()
            .replay(1)
            .autoConnect(0)
    }
```
刚开始我不明白为什么，后面我才发现如果不转化的话，由于statesObservable是一个普通的Observable，所以在订阅的时候就会发送信息，这就会导致render方法在没有Intent输入的时候就会被调用一次。
```
mViewModel.states()
            .autoDisposable(scopeProvider)
            .subscribe(this::render)
```
但是我还是不明白，就是转化成ConnectableObservable，是调用connect()才会发送数据，autoConnect(0)表示在0个订阅者的时候就会建立订阅关系，这是怎么避免render方法被触发的呢？

**Comment by qingmei2** [comment]
@CoderLengary 

你好，不好意思才看到这个issue。

请参考这篇博客, 相信能够解答你的问题哈：

[Cold Observable 和 Hot Observable](https://www.jianshu.com/p/12fb42bcf9fd)

**Comment by CoderLengary** [comment]
> @CoderLengary
> 
> 你好，不好意思才看到这个issue。
> 
> 请参考这篇博客, 相信能够解答你的问题哈：
> 
> [Cold Observable 和 Hot Observable](https://www.jianshu.com/p/12fb42bcf9fd)

我好像有点明白了，autoconnect返回的是一个正常的Observable，autoConnect(0)就代表在没有订阅者的时候就会发送数据，后面的订阅者订阅的时候就只能接收后面的数据，接收不到前面的数据，这样就保证了render在真的有数据的时候才会被调用
