### ISSUE TITLE
能了解一下为什么从Kodein换回了dagger2吗

### ISSUE THREAD

**Issue by mzzdxt** [qingmei2/MVI-Rhine#12]
看到另外一个mvvm的项目，使用了kodein来完成依赖注入，不知新项目为何又换回了dagger2呢？是应为有什么坑吗？有时间的话麻烦告知一下...多谢~

**Comment by qingmei2** [comment]
@mzzdxt 

Kodein 的缺点挺明显的，和dagger相比，首先不能识别依赖树的关系，比如dagger原理是通过在编译期生成java文件进行依赖注入，这导致如果没有提前配置对应的依赖会编译报错，但kodein不行。

其次就是文档和使用人数比较少，我之所以在项目中使用kodein，原因也是希望在个人的项目中使用比较新的技术，但用在实际项目中，这样是有风险的，资料较少导致很难快速定位问题并解决。

因此，最终我还是采用dagger2作为依赖注入框架的选型，并不是说kodein很差，相反，我很喜欢dsl的编码体验，以及full kotlin，在学习项目中，我会倾向kodein，但是在成熟项目中，dagger2有更明显的优势。
