### ISSUE TITLE
ReposViewModel文件中sortOptionSubject的作用和目的

### ISSUE THREAD

**Issue by 7-cat** [qingmei2/MVI-Rhine#2]
您好，请问一下ReposViewModel这个文件里面的如下方法：
private fun currentSortOptions(): Observable<String> {
        return sortOptionSubject.distinctUntilChanged().take(1)
}
并没有被使用到，请教一下这个方法的作用和目的是什么？

**Comment by qingmei2** [comment]
代码写的比较久了，你提的这些问题，我这几天看看

**Comment by qingmei2** [comment]
@7-cat 

这段代码忽视就可以了 = =

**Comment by qingmei2** [comment]
@7-cat 

最开始的时候，我认为开发者会需要观察  **排序条件的变更**，于是我把**排序条件的变更**作为一个返回值类型为`Observable<String>`的函数暴漏了出来；

实际上当时我的思路是错的，即使是需要把**排序条件的变更事件**向外暴漏，也不应该违反MVI **单向数据流** 和 **唯一数据源** 的准则，应该把事件也放在ViewState中。
