### ISSUE TITLE
快速点击底部按钮的情况下，ReposFragment的render方法会在onDestroyView方法之后调用，导致render方法内引用mSwipeRefreshLayout等view报空指针异常

### ISSUE THREAD

**Issue by 7-cat** [qingmei2/MVI-Rhine#3]
mViewModel.states()
            .observeOn(mSchedulerProvider.ui())
            .autoDisposable(scopeProvider)
            .subscribe(this::render)

这个autoDisposable可以设置在onDestroyView就解除订阅吗？

**Comment by 7-cat** [comment]
https://github.com/uber/AutoDispose/issues/192

目前我只能在render方法内加上
if(view==null){
    return
}

**Comment by qingmei2** [comment]
很神奇的bug，我似乎没有复现.

我看了一下`Fragment`的源码, 结束订阅的事件确实应该在 `Fragment.onDestroyView()`前就发射了：

```Java
    void performDestroyView() {
        if (mView != null) {
            mViewLifecycleRegistry.handleLifecycleEvent(Lifecycle.Event.ON_DESTROY);
        }
     //...
        onDestroyView();
     //...
    }
```

**Comment by 7-cat** [comment]
我是使用原生的Navigation对主页进行的Tab切换控制，切换Tab确实会销毁和重建Tab里面的fragment，在主页的Tab里面我又装了一个ViewPager，然后在ViewPager的每个页面里面放的是和ReposFragment一样的fragment，唯一不同的是我将childFragmentManager传入的adapter。
如果快速点击Navigation的主页tab，就会出现这个bug。。

**Comment by qingmei2** [comment]
@7-cat 

我看到了你在这个 [issue](https://github.com/oldergod/android-architecture/issues/44)中的建议，个人感觉，这只是治标而不是治本。

根本原因还是`Fragment`的生命周期，我会抽时间研究一下这个问题，就像 #4 一样，看看能不能得出什么好一点的解决方案。

**Comment by qingmei2** [comment]
@7-cat 

如果有时间，你能给`Fragment`的生命周期进行打印吗？

我刚刚看了看`FragmentNavigator`的源码, 内部是通过`replace()`函数对`Fragment`进行导航，但是和`BottomNavigationBar`配合就不知道怎么执行的了。

感觉你这种情况还是`Navigation`原生的坑...
