### ISSUE TITLE
boundaryCallback里面的onZeroItemsLoaded会被多次回调

### ISSUE THREAD

**Issue by 7-cat** [qingmei2/MVI-Rhine#4]
按照
https://developer.android.com/guide/navigation/navigation-ui?hl=zh-cN
中的指南创建Bottom navigation
然后将ReposFragment作为FragmentStatePagerAdapter的一个fragment
每次点击底部菜单，会销毁ReposFragment然后重建一个新的ReposFragment实例
每次重建一个ReposFragment之后onZeroItemsLoaded都会被多追加一次回调，但是onItemAtEndLoaded却不会多次回调。
找了好久都没找到原因，大神可否帮忙瞧瞧。。

**Comment by 7-cat** [comment]
ReposActionProcessorHolder在ReposFragment和ReposViewModel销毁的时候没有被销毁

**Comment by qingmei2** [comment]
@7-cat 

不要将`Navigation`和`BottomNavigationView`进行配合，因为原生每次点击切换都会对Fragment进行销毁和重建。

你可以参考我的项目，实际上并没有将三个sub界面通过`Navigation`配合使用，也是因为这个原因。

**Comment by qingmei2** [comment]
> ReposActionProcessorHolder在ReposFragment和ReposViewModel销毁的时候没有被销毁

这个问题我跟踪一下

**Comment by qingmei2** [comment]
@7-cat 

应该是项目中`Paging`使用的问题，不太恰当的使用导致了内存的泄漏  😢 

我通过代码对MainActivity进行关闭-打开，重复若干次，查看回收情况：

![](https://user-images.githubusercontent.com/21142152/62258370-b6d59980-b43c-11e9-9e66-bbb32cca1d52.png)

绿色框代表`ProcessorHolder`类正如我们期望的进行了内存的回收；红色框说明一些匿名内部类的实利发生了严重的内存泄漏，而且这些匿名内部类的实例都和`Paging`有关，与`Paging`无关的`Login`和`Profile`页面相关则没有此情况。

**Comment by 7-cat** [comment]
`private val initialActionTransformer =
        ObservableTransformer<ReposAction.InitialAction, ReposResult.InitialResult> { action ->
            action.flatMap<ReposResult.InitialResult> {
                repository.getReceivedPagedList(
                    boundaryCallback = object : PagedList.BoundaryCallback<Repo>() {
                        override fun onZeroItemsLoaded() {
                            this@ReposActionProcessorHolder.onZeroItemsLoaded()
                        }

                        override fun onItemAtEndLoaded(itemAtEnd: Repo) {
                            this@ReposActionProcessorHolder.onItemAtEndLoaded(itemAtEnd)
                        }
                    }
                )
                    .map(ReposResult::InitialResult)
                    .toObservable()
            }
        }`

boundaryCallback持有了ReposActionProcessorHolder的引用，按道理，下层的对象不应该持有上层的对象，如果下层的对象是app单例的（比如database对象），则会引发内存泄漏。
我也只是猜测问题出现在这里，不知道对不对，还望大神指点一下。

**Comment by 7-cat** [comment]
另外我想把下拉刷新显示列表的整个逻辑封装进一套base代码中，但是感觉好难实现。
如果app里面有20个下拉刷新列表，则要写20套mvi的代码，简直就是噩梦。

**Comment by qingmei2** [comment]
> 另外我想把下拉刷新显示列表的整个逻辑封装进一套base代码中，但是感觉好难实现。
如果app里面有20个下拉刷新列表，则要写20套mvi的代码，大部分都是重复的下拉刷新，加载数据的逻辑，代码重复度是难以接受的。

这种业务代码抽象为一个公共组件，供你的项目去复用即可，比如demo中Home界面滑动时，按钮的隐藏/显示动画的业务逻辑，就通过Observable抽了出来；

这些应该属于Rxjava的进阶使用，就不在这个issue中展开了。

**Comment by qingmei2** [comment]
> 如果下层的对象是app单例的（比如database对象），则会引发内存泄漏。

c622e5e

@7-cat 花时间研究了一下, 发生的原因找到了，有2点：

#### 1.错误的单例模式

之前的代码中，ViewModel.Factory的实例化我使用了singleton模式：

![image](https://user-images.githubusercontent.com/21142152/62273607-80197680-b470-11e9-899d-95c023590fe6.png)

**带参单例**的工厂导致了，每次实例化`ViewModel`的时候，传入的`HomeActionProcessorHolder`实际上是同一个对象！这也就说明了，为什么 *onZeroItemsLoaded会被多次回调* ， 因为`HomeActionProcessorHolder`一直没有被销毁，所以每次创建的`ViewModel`也不会被销毁，多次打开/关闭某页面，就会造成多个`ViewModel`不能被回收导致内存泄漏。

* 解决方案：移除工厂单例模式.

#### 2.为流手动配置正确的生命周期

除此之外，代码还有一些瑕疵，如果页面正在分页请求，这时关闭页面，流并没有被正确的关闭，存在内存泄漏的风险，因此，我们需要在`ViewModel.onClear()`时正确释放`ActionProcessorHolder`中的流：

```Kotlin
class HomeActionProcessorHolder {
// ...
    fun onViewModelCleared() {
        if (mViewModelClearEventPublisher.hasComplete())
            throw IllegalStateException("can't call onViewModelCleared() repeatedly.")

        mViewModelClearEventPublisher.onNext(0)
        mViewModelClearEventPublisher.onComplete()

        receivedEventsLoadingEventSubject.onComplete()
    }
}
```

#### 3.顺手重构了app

顺带的，`Kodein`在Debug时候太麻烦了，有很多不便，于是我 **顺手** 把`Kodein`替换成了`dagger.android`，于是接下来的调试就顺风顺水了～  😸

**Comment by qingmei2** [comment]
@7-cat 

如果没有问题的话，请关闭issue哈

**Comment by 7-cat** [comment]
移除工厂单例模式之后，即使每次生成了不同的HomeActionProcessorHolder实例，
在销毁HomeFragment之后（onDetach被调用），ViewModel的onCleared方法随即立即被调用，但是ViewModel所引用的HomeActionProcessorHolder并没有立即调用finalize()方法，如果重新实例化一个HomeFragment，onZeroItemsLoaded会被调用两次。

**Comment by 7-cat** [comment]
在ViewModel中增加如下代码：
    override fun onCleared() {
        super.onCleared()
        actionProcessorHolder.isEnd = true
    }


在ActionProcessorHolder增加如下代码
//对应ViewModel是否已经销毁
var isEnd = false
override fun onZeroItemsLoaded() {
                                        if (isEnd) {
                                            return   //此处打断点
                                        }
...
}
断点打到return这一行，会debug到

**Comment by qingmei2** [comment]
> 断点打到return这一行，会debug到

这个问题请问最新的代码可以复现吗，我试了试并没有成功复现

**Comment by 7-cat** [comment]
1.错误的单例模式
2.为流手动配置正确的生命周期
你说的这两点我都按照你的代码修改了，以前会出现重复调用onZeroItemsLoaded的情况减少了。
但是在如下情况下还是会出现：
步骤1:设置后端接口返回30条数据，
步骤1:首次加载将30条数据加载到app，让加载数据的fragment销毁重建几次
步骤1:设置后端接口返回0条数据
步骤1:下拉刷新，出现重复调用onZeroItemsLoaded
<img width="566" alt="WX20190801-201724@2x" src="https://user-images.githubusercontent.com/26700637/62293028-3e9dc100-b49a-11e9-846d-3183fd8cc149.png">

**Comment by qingmei2** [comment]
> 有点想回退到MVVM了，为这些问题折腾太久了。
> 而且intent->action->result->ViewState这条链路太长了，代码太啰嗦了，感觉好绕，而且跟react的redux相比，差距还是很大，用起来很别扭。

这个看个人哈，我个人比较喜欢MVI模式，原因就是因为MVVM在涉及复杂页面时，太多的observable的订阅导致代码可读性降低，但是如果代码规范的话，问题也不会很大
