### ISSUE TITLE
当下拉刷新加载数据的时候如果返回空列表，distinctUntilChanged引起的刷新状态无法恢复

### ISSUE THREAD

**Issue by 7-cat** [qingmei2/MVI-Rhine#5]
ReposViewModel里面compose()方法中的distinctUntilChanged()操作符：
当下拉刷新加载数据的时候如果返回空列表，下拉刷新之后状态无法回复，一直处于刷新状态，去掉distinctUntilChanged()之后就可以了，请教一下去掉distinctUntilChanged这个操作符会产生什么影响？

**Comment by qingmei2** [comment]
`distinctUntilChanged `是对序列中相同的状态进行过滤，你说的这种情况，应该是业务代码写的有问题，`distinctUntilChanged`不应该被删除。
