### ISSUE TITLE
首页 error:HTTP 404 NOT FOUND

### ISSUE THREAD

**Issue by 4what2do** [qingmei2/MVI-Rhine#7]

**Comment by qingmei2** [comment]
暂时没有复现这个情况，持续观察。

**Comment by 4what2do** [comment]
怎么没用kodein

**Comment by 4what2do** [comment]
原因不赘述了https://github.com/qingmei2/MVVM-Rhine/commit/12de83a94657d1ce85e3d59c079d07c3c855787c
