### ISSUE TITLE
关于Adapter的Item事件传递

### ISSUE THREAD

**Issue by CoderLengary** [qingmei2/MVI-Rhine#8]
对于Adapter中的Item中的点击事件，项目中的操作是做成一个PublishSubject暴露出来给Fragment。就拿点击Item后跳转来说吧，就是PublishSubject onNext一个事件给Fragment，Fragment接收到后执行跳转。
```
mAdapter.observeEvent()
         .doOnNext { event ->
             when (event) {
                 is HomePagedListItemEvent.ClickEvent -> {
                         context?.jumpBrowser(event.url)
                           }
                     }
         }
          .autoDisposable(scopeProvider)
          .subscribe()
```
按照一个完整的MVI模式的话，它并没有走Intent -> Action -> Result -> ViewState的路，这样是不是违背了这个原则呢

**Comment by qingmei2** [comment]
@CoderLengary 

我认为目前这样的做法是可以的，因为我理解的所谓的架构模式，最重要的一点是 **代码规范** ，将整个项目的开发流程用特定的一种模式（或者思想）规范起来，方便以后的开发者能通过这个思想，快速对既有的项目进行修复和迭代。

MVI的最大优势在于 **状态管理**，任何一次render都意味着状态的变更，这里的状态指的是 **开发者关心的状态** ， 而不是页面所有的状态——如果一个item的点击事件，仅仅是通知跳转页面，那么这个事件就不需要影响到 **开发者需要关心的状态** ，仅仅把这个事件消费掉就可以了。

反过来说，如果这个点击事件，影响到了业务的流程和状态的变更，比如点击Item进行点赞👍，这时候，将这个事件作为一个`Intent`加入到`Observable`中，就有意义了。

以上都是我自己的一些理解，希望能够帮助到你。

**Comment by CoderLengary** [comment]
感谢你的回复，

> 任何一次render都意味着状态的变更，这里的状态指的是 页面UI和业务的状态

这句话让我顿悟了

**Comment by qingmei2** [comment]
那我就把issue关闭了 😄 🤝
